package com.google.android.gms.internal.mlkit_vision_barcode;

import androidx.datastore.preferences.protobuf.Y;
import com.google.android.libraries.barhopper.RecognitionOptions;
import h4.C1083c;
import h4.InterfaceC1084d;
import h4.InterfaceC1085e;
import java.util.HashMap;
/* loaded from: classes.dex */
final class zzkv implements InterfaceC1084d {
    private static final C1083c zzA;
    private static final C1083c zzB;
    private static final C1083c zzC;
    private static final C1083c zzD;
    private static final C1083c zzE;
    private static final C1083c zzF;
    private static final C1083c zzG;
    private static final C1083c zzH;
    private static final C1083c zzI;
    private static final C1083c zzJ;
    private static final C1083c zzK;
    private static final C1083c zzL;
    private static final C1083c zzM;
    private static final C1083c zzN;
    private static final C1083c zzO;
    private static final C1083c zzP;
    private static final C1083c zzQ;
    private static final C1083c zzR;
    private static final C1083c zzS;
    private static final C1083c zzT;
    private static final C1083c zzU;
    private static final C1083c zzV;
    private static final C1083c zzW;
    private static final C1083c zzX;
    private static final C1083c zzY;
    private static final C1083c zzZ;
    static final zzkv zza = new zzkv();
    private static final C1083c zzaA;
    private static final C1083c zzaB;
    private static final C1083c zzaC;
    private static final C1083c zzaD;
    private static final C1083c zzaE;
    private static final C1083c zzaF;
    private static final C1083c zzaG;
    private static final C1083c zzaH;
    private static final C1083c zzaI;
    private static final C1083c zzaJ;
    private static final C1083c zzaK;
    private static final C1083c zzaL;
    private static final C1083c zzaM;
    private static final C1083c zzaN;
    private static final C1083c zzaO;
    private static final C1083c zzaP;
    private static final C1083c zzaQ;
    private static final C1083c zzaR;
    private static final C1083c zzaS;
    private static final C1083c zzaT;
    private static final C1083c zzaU;
    private static final C1083c zzaV;
    private static final C1083c zzaW;
    private static final C1083c zzaX;
    private static final C1083c zzaY;
    private static final C1083c zzaZ;
    private static final C1083c zzaa;
    private static final C1083c zzab;
    private static final C1083c zzac;
    private static final C1083c zzad;
    private static final C1083c zzae;
    private static final C1083c zzaf;
    private static final C1083c zzag;
    private static final C1083c zzah;
    private static final C1083c zzai;
    private static final C1083c zzaj;
    private static final C1083c zzak;
    private static final C1083c zzal;
    private static final C1083c zzam;
    private static final C1083c zzan;
    private static final C1083c zzao;
    private static final C1083c zzap;
    private static final C1083c zzaq;
    private static final C1083c zzar;
    private static final C1083c zzas;
    private static final C1083c zzat;
    private static final C1083c zzau;
    private static final C1083c zzav;
    private static final C1083c zzaw;
    private static final C1083c zzax;
    private static final C1083c zzay;
    private static final C1083c zzaz;
    private static final C1083c zzb;
    private static final C1083c zzba;
    private static final C1083c zzbb;
    private static final C1083c zzbc;
    private static final C1083c zzbd;
    private static final C1083c zzbe;
    private static final C1083c zzbf;
    private static final C1083c zzbg;
    private static final C1083c zzbh;
    private static final C1083c zzbi;
    private static final C1083c zzbj;
    private static final C1083c zzbk;
    private static final C1083c zzbl;
    private static final C1083c zzbm;
    private static final C1083c zzbn;
    private static final C1083c zzbo;
    private static final C1083c zzbp;
    private static final C1083c zzbq;
    private static final C1083c zzbr;
    private static final C1083c zzbs;
    private static final C1083c zzbt;
    private static final C1083c zzbu;
    private static final C1083c zzbv;
    private static final C1083c zzbw;
    private static final C1083c zzbx;
    private static final C1083c zzby;
    private static final C1083c zzc;
    private static final C1083c zzd;
    private static final C1083c zze;
    private static final C1083c zzf;
    private static final C1083c zzg;
    private static final C1083c zzh;
    private static final C1083c zzi;
    private static final C1083c zzj;
    private static final C1083c zzk;
    private static final C1083c zzl;
    private static final C1083c zzm;
    private static final C1083c zzn;
    private static final C1083c zzo;
    private static final C1083c zzp;
    private static final C1083c zzq;
    private static final C1083c zzr;
    private static final C1083c zzs;
    private static final C1083c zzt;
    private static final C1083c zzu;
    private static final C1083c zzv;
    private static final C1083c zzw;
    private static final C1083c zzx;
    private static final C1083c zzy;
    private static final C1083c zzz;

    static {
        zzfe g3 = Y.g(1);
        HashMap hashMap = new HashMap();
        hashMap.put(g3.annotationType(), g3);
        zzb = new C1083c("systemInfo", Y.n(hashMap));
        zzfe g4 = Y.g(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(g4.annotationType(), g4);
        zzc = new C1083c("eventName", Y.n(hashMap2));
        zzfe g8 = Y.g(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(g8.annotationType(), g8);
        zzd = new C1083c("isThickClient", Y.n(hashMap3));
        zzfe g9 = Y.g(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(g9.annotationType(), g9);
        zze = new C1083c("clientType", Y.n(hashMap4));
        zzfe g10 = Y.g(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(g10.annotationType(), g10);
        zzf = new C1083c("modelDownloadLogEvent", Y.n(hashMap5));
        zzfe g11 = Y.g(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(g11.annotationType(), g11);
        zzg = new C1083c("customModelLoadLogEvent", Y.n(hashMap6));
        zzfe g12 = Y.g(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(g12.annotationType(), g12);
        zzh = new C1083c("customModelInferenceLogEvent", Y.n(hashMap7));
        zzfe g13 = Y.g(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(g13.annotationType(), g13);
        zzi = new C1083c("customModelCreateLogEvent", Y.n(hashMap8));
        zzfe g14 = Y.g(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(g14.annotationType(), g14);
        zzj = new C1083c("onDeviceFaceDetectionLogEvent", Y.n(hashMap9));
        zzfe g15 = Y.g(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(g15.annotationType(), g15);
        zzk = new C1083c("onDeviceFaceLoadLogEvent", Y.n(hashMap10));
        zzfe g16 = Y.g(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(g16.annotationType(), g16);
        zzl = new C1083c("onDeviceTextDetectionLogEvent", Y.n(hashMap11));
        zzfe g17 = Y.g(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(g17.annotationType(), g17);
        zzm = new C1083c("onDeviceTextDetectionLoadLogEvent", Y.n(hashMap12));
        zzfe g18 = Y.g(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(g18.annotationType(), g18);
        zzn = new C1083c("onDeviceBarcodeDetectionLogEvent", Y.n(hashMap13));
        zzfe g19 = Y.g(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(g19.annotationType(), g19);
        zzo = new C1083c("onDeviceBarcodeLoadLogEvent", Y.n(hashMap14));
        zzfe g20 = Y.g(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(g20.annotationType(), g20);
        zzp = new C1083c("onDeviceImageLabelCreateLogEvent", Y.n(hashMap15));
        zzfe g21 = Y.g(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(g21.annotationType(), g21);
        zzq = new C1083c("onDeviceImageLabelLoadLogEvent", Y.n(hashMap16));
        zzfe g22 = Y.g(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(g22.annotationType(), g22);
        zzr = new C1083c("onDeviceImageLabelDetectionLogEvent", Y.n(hashMap17));
        zzfe g23 = Y.g(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(g23.annotationType(), g23);
        zzs = new C1083c("onDeviceObjectCreateLogEvent", Y.n(hashMap18));
        zzfe g24 = Y.g(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(g24.annotationType(), g24);
        zzt = new C1083c("onDeviceObjectLoadLogEvent", Y.n(hashMap19));
        zzfe g25 = Y.g(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(g25.annotationType(), g25);
        zzu = new C1083c("onDeviceObjectInferenceLogEvent", Y.n(hashMap20));
        zzfe g26 = Y.g(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(g26.annotationType(), g26);
        zzv = new C1083c("onDevicePoseDetectionLogEvent", Y.n(hashMap21));
        zzfe g27 = Y.g(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(g27.annotationType(), g27);
        zzw = new C1083c("onDeviceSegmentationLogEvent", Y.n(hashMap22));
        zzfe g28 = Y.g(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(g28.annotationType(), g28);
        zzx = new C1083c("onDeviceSmartReplyLogEvent", Y.n(hashMap23));
        zzfe g29 = Y.g(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(g29.annotationType(), g29);
        zzy = new C1083c("onDeviceLanguageIdentificationLogEvent", Y.n(hashMap24));
        zzfe g30 = Y.g(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(g30.annotationType(), g30);
        zzz = new C1083c("onDeviceTranslationLogEvent", Y.n(hashMap25));
        zzfe g31 = Y.g(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(g31.annotationType(), g31);
        zzA = new C1083c("cloudFaceDetectionLogEvent", Y.n(hashMap26));
        zzfe g32 = Y.g(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(g32.annotationType(), g32);
        zzB = new C1083c("cloudCropHintDetectionLogEvent", Y.n(hashMap27));
        zzfe g33 = Y.g(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(g33.annotationType(), g33);
        zzC = new C1083c("cloudDocumentTextDetectionLogEvent", Y.n(hashMap28));
        zzfe g34 = Y.g(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(g34.annotationType(), g34);
        zzD = new C1083c("cloudImagePropertiesDetectionLogEvent", Y.n(hashMap29));
        zzfe g35 = Y.g(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(g35.annotationType(), g35);
        zzE = new C1083c("cloudImageLabelDetectionLogEvent", Y.n(hashMap30));
        zzfe g36 = Y.g(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(g36.annotationType(), g36);
        zzF = new C1083c("cloudLandmarkDetectionLogEvent", Y.n(hashMap31));
        zzfe g37 = Y.g(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(g37.annotationType(), g37);
        zzG = new C1083c("cloudLogoDetectionLogEvent", Y.n(hashMap32));
        zzfe g38 = Y.g(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(g38.annotationType(), g38);
        zzH = new C1083c("cloudSafeSearchDetectionLogEvent", Y.n(hashMap33));
        zzfe g39 = Y.g(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(g39.annotationType(), g39);
        zzI = new C1083c("cloudTextDetectionLogEvent", Y.n(hashMap34));
        zzfe g40 = Y.g(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(g40.annotationType(), g40);
        zzJ = new C1083c("cloudWebSearchDetectionLogEvent", Y.n(hashMap35));
        zzfe g41 = Y.g(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(g41.annotationType(), g41);
        zzK = new C1083c("automlImageLabelingCreateLogEvent", Y.n(hashMap36));
        zzfe g42 = Y.g(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(g42.annotationType(), g42);
        zzL = new C1083c("automlImageLabelingLoadLogEvent", Y.n(hashMap37));
        zzfe g43 = Y.g(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(g43.annotationType(), g43);
        zzM = new C1083c("automlImageLabelingInferenceLogEvent", Y.n(hashMap38));
        zzfe g44 = Y.g(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(g44.annotationType(), g44);
        zzN = new C1083c("isModelDownloadedLogEvent", Y.n(hashMap39));
        zzfe g45 = Y.g(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(g45.annotationType(), g45);
        zzO = new C1083c("deleteModelLogEvent", Y.n(hashMap40));
        zzfe g46 = Y.g(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(g46.annotationType(), g46);
        zzP = new C1083c("aggregatedAutomlImageLabelingInferenceLogEvent", Y.n(hashMap41));
        zzfe g47 = Y.g(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(g47.annotationType(), g47);
        zzQ = new C1083c("aggregatedCustomModelInferenceLogEvent", Y.n(hashMap42));
        zzfe g48 = Y.g(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(g48.annotationType(), g48);
        zzR = new C1083c("aggregatedOnDeviceFaceDetectionLogEvent", Y.n(hashMap43));
        zzfe g49 = Y.g(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(g49.annotationType(), g49);
        zzS = new C1083c("aggregatedOnDeviceBarcodeDetectionLogEvent", Y.n(hashMap44));
        zzfe g50 = Y.g(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(g50.annotationType(), g50);
        zzT = new C1083c("aggregatedOnDeviceImageLabelDetectionLogEvent", Y.n(hashMap45));
        zzfe g51 = Y.g(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(g51.annotationType(), g51);
        zzU = new C1083c("aggregatedOnDeviceObjectInferenceLogEvent", Y.n(hashMap46));
        zzfe g52 = Y.g(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(g52.annotationType(), g52);
        zzV = new C1083c("aggregatedOnDeviceTextDetectionLogEvent", Y.n(hashMap47));
        zzfe g53 = Y.g(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(g53.annotationType(), g53);
        zzW = new C1083c("aggregatedOnDevicePoseDetectionLogEvent", Y.n(hashMap48));
        zzfe g54 = Y.g(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(g54.annotationType(), g54);
        zzX = new C1083c("aggregatedOnDeviceSegmentationLogEvent", Y.n(hashMap49));
        zzfe g55 = Y.g(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(g55.annotationType(), g55);
        zzY = new C1083c("pipelineAccelerationInferenceEvents", Y.n(hashMap50));
        zzfe g56 = Y.g(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(g56.annotationType(), g56);
        zzZ = new C1083c("remoteConfigLogEvent", Y.n(hashMap51));
        zzfe g57 = Y.g(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(g57.annotationType(), g57);
        zzaa = new C1083c("inputImageConstructionLogEvent", Y.n(hashMap52));
        zzfe g58 = Y.g(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(g58.annotationType(), g58);
        zzab = new C1083c("leakedHandleEvent", Y.n(hashMap53));
        zzfe g59 = Y.g(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(g59.annotationType(), g59);
        zzac = new C1083c("cameraSourceLogEvent", Y.n(hashMap54));
        zzfe g60 = Y.g(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(g60.annotationType(), g60);
        zzad = new C1083c("imageLabelOptionalModuleLogEvent", Y.n(hashMap55));
        zzfe g61 = Y.g(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(g61.annotationType(), g61);
        zzae = new C1083c("languageIdentificationOptionalModuleLogEvent", Y.n(hashMap56));
        zzfe g62 = Y.g(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(g62.annotationType(), g62);
        zzaf = new C1083c("faceDetectionOptionalModuleLogEvent", Y.n(hashMap57));
        zzfe g63 = Y.g(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(g63.annotationType(), g63);
        zzag = new C1083c("documentDetectionOptionalModuleLogEvent", Y.n(hashMap58));
        zzfe g64 = Y.g(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(g64.annotationType(), g64);
        zzah = new C1083c("documentCroppingOptionalModuleLogEvent", Y.n(hashMap59));
        zzfe g65 = Y.g(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(g65.annotationType(), g65);
        zzai = new C1083c("documentEnhancementOptionalModuleLogEvent", Y.n(hashMap60));
        zzfe g66 = Y.g(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(g66.annotationType(), g66);
        zzaj = new C1083c("nlClassifierOptionalModuleLogEvent", Y.n(hashMap61));
        zzfe g67 = Y.g(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(g67.annotationType(), g67);
        zzak = new C1083c("nlClassifierClientLibraryLogEvent", Y.n(hashMap62));
        zzfe g68 = Y.g(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(g68.annotationType(), g68);
        zzal = new C1083c("accelerationAllowlistLogEvent", Y.n(hashMap63));
        zzfe g69 = Y.g(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(g69.annotationType(), g69);
        zzam = new C1083c("toxicityDetectionCreateEvent", Y.n(hashMap64));
        zzfe g70 = Y.g(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(g70.annotationType(), g70);
        zzan = new C1083c("toxicityDetectionLoadEvent", Y.n(hashMap65));
        zzfe g71 = Y.g(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(g71.annotationType(), g71);
        zzao = new C1083c("toxicityDetectionInferenceEvent", Y.n(hashMap66));
        zzfe g72 = Y.g(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(g72.annotationType(), g72);
        zzap = new C1083c("barcodeDetectionOptionalModuleLogEvent", Y.n(hashMap67));
        zzfe g73 = Y.g(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(g73.annotationType(), g73);
        zzaq = new C1083c("customImageLabelOptionalModuleLogEvent", Y.n(hashMap68));
        zzfe g74 = Y.g(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(g74.annotationType(), g74);
        zzar = new C1083c("codeScannerScanApiEvent", Y.n(hashMap69));
        zzfe g75 = Y.g(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(g75.annotationType(), g75);
        zzas = new C1083c("codeScannerOptionalModuleEvent", Y.n(hashMap70));
        zzfe g76 = Y.g(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(g76.annotationType(), g76);
        zzat = new C1083c("onDeviceExplicitContentCreateLogEvent", Y.n(hashMap71));
        zzfe g77 = Y.g(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(g77.annotationType(), g77);
        zzau = new C1083c("onDeviceExplicitContentLoadLogEvent", Y.n(hashMap72));
        zzfe g78 = Y.g(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(g78.annotationType(), g78);
        zzav = new C1083c("onDeviceExplicitContentInferenceLogEvent", Y.n(hashMap73));
        zzfe g79 = Y.g(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(g79.annotationType(), g79);
        zzaw = new C1083c("aggregatedOnDeviceExplicitContentLogEvent", Y.n(hashMap74));
        zzfe g80 = Y.g(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(g80.annotationType(), g80);
        zzax = new C1083c("onDeviceFaceMeshCreateLogEvent", Y.n(hashMap75));
        zzfe g81 = Y.g(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(g81.annotationType(), g81);
        zzay = new C1083c("onDeviceFaceMeshLoadLogEvent", Y.n(hashMap76));
        zzfe g82 = Y.g(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(g82.annotationType(), g82);
        zzaz = new C1083c("onDeviceFaceMeshLogEvent", Y.n(hashMap77));
        zzfe g83 = Y.g(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(g83.annotationType(), g83);
        zzaA = new C1083c("aggregatedOnDeviceFaceMeshLogEvent", Y.n(hashMap78));
        zzfe g84 = Y.g(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(g84.annotationType(), g84);
        zzaB = new C1083c("smartReplyOptionalModuleLogEvent", Y.n(hashMap79));
        zzfe g85 = Y.g(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(g85.annotationType(), g85);
        zzaC = new C1083c("textDetectionOptionalModuleLogEvent", Y.n(hashMap80));
        zzfe g86 = Y.g(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(g86.annotationType(), g86);
        zzaD = new C1083c("onDeviceImageQualityAnalysisCreateLogEvent", Y.n(hashMap81));
        zzfe g87 = Y.g(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(g87.annotationType(), g87);
        zzaE = new C1083c("onDeviceImageQualityAnalysisLoadLogEvent", Y.n(hashMap82));
        zzfe g88 = Y.g(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(g88.annotationType(), g88);
        zzaF = new C1083c("onDeviceImageQualityAnalysisLogEvent", Y.n(hashMap83));
        zzfe g89 = Y.g(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(g89.annotationType(), g89);
        zzaG = new C1083c("aggregatedOnDeviceImageQualityAnalysisLogEvent", Y.n(hashMap84));
        zzfe g90 = Y.g(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(g90.annotationType(), g90);
        zzaH = new C1083c("imageQualityAnalysisOptionalModuleLogEvent", Y.n(hashMap85));
        zzfe g91 = Y.g(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(g91.annotationType(), g91);
        zzaI = new C1083c("imageCaptioningOptionalModuleLogEvent", Y.n(hashMap86));
        zzfe g92 = Y.g(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(g92.annotationType(), g92);
        zzaJ = new C1083c("onDeviceImageCaptioningCreateLogEvent", Y.n(hashMap87));
        zzfe g93 = Y.g(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(g93.annotationType(), g93);
        zzaK = new C1083c("onDeviceImageCaptioningLoadLogEvent", Y.n(hashMap88));
        zzfe g94 = Y.g(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(g94.annotationType(), g94);
        zzaL = new C1083c("onDeviceImageCaptioningInferenceLogEvent", Y.n(hashMap89));
        zzfe g95 = Y.g(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(g95.annotationType(), g95);
        zzaM = new C1083c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", Y.n(hashMap90));
        zzfe g96 = Y.g(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(g96.annotationType(), g96);
        zzaN = new C1083c("onDeviceDocumentDetectionCreateLogEvent", Y.n(hashMap91));
        zzfe g97 = Y.g(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(g97.annotationType(), g97);
        zzaO = new C1083c("onDeviceDocumentDetectionLoadLogEvent", Y.n(hashMap92));
        zzfe g98 = Y.g(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(g98.annotationType(), g98);
        zzaP = new C1083c("onDeviceDocumentDetectionLogEvent", Y.n(hashMap93));
        zzfe g99 = Y.g(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(g99.annotationType(), g99);
        zzaQ = new C1083c("aggregatedOnDeviceDocumentDetectionLogEvent", Y.n(hashMap94));
        zzfe g100 = Y.g(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(g100.annotationType(), g100);
        zzaR = new C1083c("onDeviceDocumentCroppingCreateLogEvent", Y.n(hashMap95));
        zzfe g101 = Y.g(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(g101.annotationType(), g101);
        zzaS = new C1083c("onDeviceDocumentCroppingLoadLogEvent", Y.n(hashMap96));
        zzfe g102 = Y.g(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(g102.annotationType(), g102);
        zzaT = new C1083c("onDeviceDocumentCroppingLogEvent", Y.n(hashMap97));
        zzfe g103 = Y.g(101);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(g103.annotationType(), g103);
        zzaU = new C1083c("aggregatedOnDeviceDocumentCroppingLogEvent", Y.n(hashMap98));
        zzfe g104 = Y.g(102);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(g104.annotationType(), g104);
        zzaV = new C1083c("onDeviceDocumentEnhancementCreateLogEvent", Y.n(hashMap99));
        zzfe g105 = Y.g(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(g105.annotationType(), g105);
        zzaW = new C1083c("onDeviceDocumentEnhancementLoadLogEvent", Y.n(hashMap100));
        zzfe g106 = Y.g(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(g106.annotationType(), g106);
        zzaX = new C1083c("onDeviceDocumentEnhancementLogEvent", Y.n(hashMap101));
        zzfe g107 = Y.g(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(g107.annotationType(), g107);
        zzaY = new C1083c("aggregatedOnDeviceDocumentEnhancementLogEvent", Y.n(hashMap102));
        zzfe g108 = Y.g(106);
        HashMap hashMap103 = new HashMap();
        hashMap103.put(g108.annotationType(), g108);
        zzaZ = new C1083c("scannerAutoZoomEvent", Y.n(hashMap103));
        zzfe g109 = Y.g(107);
        HashMap hashMap104 = new HashMap();
        hashMap104.put(g109.annotationType(), g109);
        zzba = new C1083c("lowLightAutoExposureComputationEvent", Y.n(hashMap104));
        zzfe g110 = Y.g(108);
        HashMap hashMap105 = new HashMap();
        hashMap105.put(g110.annotationType(), g110);
        zzbb = new C1083c("lowLightFrameProcessEvent", Y.n(hashMap105));
        zzfe g111 = Y.g(109);
        HashMap hashMap106 = new HashMap();
        hashMap106.put(g111.annotationType(), g111);
        zzbc = new C1083c("lowLightSceneDetectionEvent", Y.n(hashMap106));
        zzfe g112 = Y.g(110);
        HashMap hashMap107 = new HashMap();
        hashMap107.put(g112.annotationType(), g112);
        zzbd = new C1083c("onDeviceStainRemovalLogEvent", Y.n(hashMap107));
        zzfe g113 = Y.g(111);
        HashMap hashMap108 = new HashMap();
        hashMap108.put(g113.annotationType(), g113);
        zzbe = new C1083c("aggregatedOnDeviceStainRemovalLogEvent", Y.n(hashMap108));
        zzbf = Y.s(112, C1083c.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = Y.s(113, C1083c.a("onDeviceShadowRemovalLogEvent"));
        zzbh = Y.s(114, C1083c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = Y.s(115, C1083c.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = Y.s(116, C1083c.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = Y.s(117, C1083c.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = Y.s(118, C1083c.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = Y.s(119, C1083c.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = Y.s(120, C1083c.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = Y.s(121, C1083c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = Y.s(122, C1083c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = Y.s(123, C1083c.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = Y.s(124, C1083c.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = Y.s(125, C1083c.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = Y.s(126, C1083c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = Y.s(127, C1083c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = Y.s(RecognitionOptions.ITF, C1083c.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = Y.s(129, C1083c.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = Y.s(130, C1083c.a("documentScannerUiModuleScreenClickEvent"));
        zzby = Y.s(131, C1083c.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzkv() {
    }

    @Override // h4.InterfaceC1081a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzrf zzrfVar = (zzrf) obj;
        InterfaceC1085e interfaceC1085e = (InterfaceC1085e) obj2;
        interfaceC1085e.add(zzb, zzrfVar.zzg());
        interfaceC1085e.add(zzc, zzrfVar.zzc());
        interfaceC1085e.add(zzd, (Object) null);
        interfaceC1085e.add(zze, zzrfVar.zzb());
        interfaceC1085e.add(zzf, (Object) null);
        interfaceC1085e.add(zzg, (Object) null);
        interfaceC1085e.add(zzh, (Object) null);
        interfaceC1085e.add(zzi, (Object) null);
        interfaceC1085e.add(zzj, (Object) null);
        interfaceC1085e.add(zzk, (Object) null);
        interfaceC1085e.add(zzl, (Object) null);
        interfaceC1085e.add(zzm, (Object) null);
        interfaceC1085e.add(zzn, zzrfVar.zzd());
        interfaceC1085e.add(zzo, zzrfVar.zze());
        interfaceC1085e.add(zzp, (Object) null);
        interfaceC1085e.add(zzq, (Object) null);
        interfaceC1085e.add(zzr, (Object) null);
        interfaceC1085e.add(zzs, (Object) null);
        interfaceC1085e.add(zzt, (Object) null);
        interfaceC1085e.add(zzu, (Object) null);
        interfaceC1085e.add(zzv, (Object) null);
        interfaceC1085e.add(zzw, (Object) null);
        interfaceC1085e.add(zzx, (Object) null);
        interfaceC1085e.add(zzy, (Object) null);
        interfaceC1085e.add(zzz, (Object) null);
        interfaceC1085e.add(zzA, (Object) null);
        interfaceC1085e.add(zzB, (Object) null);
        interfaceC1085e.add(zzC, (Object) null);
        interfaceC1085e.add(zzD, (Object) null);
        interfaceC1085e.add(zzE, (Object) null);
        interfaceC1085e.add(zzF, (Object) null);
        interfaceC1085e.add(zzG, (Object) null);
        interfaceC1085e.add(zzH, (Object) null);
        interfaceC1085e.add(zzI, (Object) null);
        interfaceC1085e.add(zzJ, (Object) null);
        interfaceC1085e.add(zzK, (Object) null);
        interfaceC1085e.add(zzL, (Object) null);
        interfaceC1085e.add(zzM, (Object) null);
        interfaceC1085e.add(zzN, (Object) null);
        interfaceC1085e.add(zzO, (Object) null);
        interfaceC1085e.add(zzP, (Object) null);
        interfaceC1085e.add(zzQ, (Object) null);
        interfaceC1085e.add(zzR, (Object) null);
        interfaceC1085e.add(zzS, zzrfVar.zza());
        interfaceC1085e.add(zzT, (Object) null);
        interfaceC1085e.add(zzU, (Object) null);
        interfaceC1085e.add(zzV, (Object) null);
        interfaceC1085e.add(zzW, (Object) null);
        interfaceC1085e.add(zzX, (Object) null);
        interfaceC1085e.add(zzY, (Object) null);
        interfaceC1085e.add(zzZ, (Object) null);
        interfaceC1085e.add(zzaa, (Object) null);
        interfaceC1085e.add(zzab, (Object) null);
        interfaceC1085e.add(zzac, (Object) null);
        interfaceC1085e.add(zzad, (Object) null);
        interfaceC1085e.add(zzae, (Object) null);
        interfaceC1085e.add(zzaf, (Object) null);
        interfaceC1085e.add(zzag, (Object) null);
        interfaceC1085e.add(zzah, (Object) null);
        interfaceC1085e.add(zzai, (Object) null);
        interfaceC1085e.add(zzaj, (Object) null);
        interfaceC1085e.add(zzak, (Object) null);
        interfaceC1085e.add(zzal, (Object) null);
        interfaceC1085e.add(zzam, (Object) null);
        interfaceC1085e.add(zzan, (Object) null);
        interfaceC1085e.add(zzao, (Object) null);
        interfaceC1085e.add(zzap, (Object) null);
        interfaceC1085e.add(zzaq, (Object) null);
        interfaceC1085e.add(zzar, (Object) null);
        interfaceC1085e.add(zzas, (Object) null);
        interfaceC1085e.add(zzat, (Object) null);
        interfaceC1085e.add(zzau, (Object) null);
        interfaceC1085e.add(zzav, (Object) null);
        interfaceC1085e.add(zzaw, (Object) null);
        interfaceC1085e.add(zzax, (Object) null);
        interfaceC1085e.add(zzay, (Object) null);
        interfaceC1085e.add(zzaz, (Object) null);
        interfaceC1085e.add(zzaA, (Object) null);
        interfaceC1085e.add(zzaB, (Object) null);
        interfaceC1085e.add(zzaC, (Object) null);
        interfaceC1085e.add(zzaD, (Object) null);
        interfaceC1085e.add(zzaE, (Object) null);
        interfaceC1085e.add(zzaF, (Object) null);
        interfaceC1085e.add(zzaG, (Object) null);
        interfaceC1085e.add(zzaH, (Object) null);
        interfaceC1085e.add(zzaI, (Object) null);
        interfaceC1085e.add(zzaJ, (Object) null);
        interfaceC1085e.add(zzaK, (Object) null);
        interfaceC1085e.add(zzaL, (Object) null);
        interfaceC1085e.add(zzaM, (Object) null);
        interfaceC1085e.add(zzaN, (Object) null);
        interfaceC1085e.add(zzaO, (Object) null);
        interfaceC1085e.add(zzaP, (Object) null);
        interfaceC1085e.add(zzaQ, (Object) null);
        interfaceC1085e.add(zzaR, (Object) null);
        interfaceC1085e.add(zzaS, (Object) null);
        interfaceC1085e.add(zzaT, (Object) null);
        interfaceC1085e.add(zzaU, (Object) null);
        interfaceC1085e.add(zzaV, (Object) null);
        interfaceC1085e.add(zzaW, (Object) null);
        interfaceC1085e.add(zzaX, (Object) null);
        interfaceC1085e.add(zzaY, (Object) null);
        interfaceC1085e.add(zzaZ, zzrfVar.zzf());
        interfaceC1085e.add(zzba, (Object) null);
        interfaceC1085e.add(zzbb, (Object) null);
        interfaceC1085e.add(zzbc, (Object) null);
        interfaceC1085e.add(zzbd, (Object) null);
        interfaceC1085e.add(zzbe, (Object) null);
        interfaceC1085e.add(zzbf, (Object) null);
        interfaceC1085e.add(zzbg, (Object) null);
        interfaceC1085e.add(zzbh, (Object) null);
        interfaceC1085e.add(zzbi, (Object) null);
        interfaceC1085e.add(zzbj, (Object) null);
        interfaceC1085e.add(zzbk, (Object) null);
        interfaceC1085e.add(zzbl, (Object) null);
        interfaceC1085e.add(zzbm, (Object) null);
        interfaceC1085e.add(zzbn, (Object) null);
        interfaceC1085e.add(zzbo, (Object) null);
        interfaceC1085e.add(zzbp, (Object) null);
        interfaceC1085e.add(zzbq, (Object) null);
        interfaceC1085e.add(zzbr, (Object) null);
        interfaceC1085e.add(zzbs, (Object) null);
        interfaceC1085e.add(zzbt, (Object) null);
        interfaceC1085e.add(zzbu, (Object) null);
        interfaceC1085e.add(zzbv, (Object) null);
        interfaceC1085e.add(zzbw, (Object) null);
        interfaceC1085e.add(zzbx, (Object) null);
        interfaceC1085e.add(zzby, (Object) null);
    }
}
