package com.google.android.gms.internal.mlkit_common;

import androidx.datastore.preferences.protobuf.Y;
import com.google.android.libraries.barhopper.RecognitionOptions;
import h4.C1083c;
import h4.InterfaceC1084d;
import h4.InterfaceC1085e;
import java.util.HashMap;
/* loaded from: classes.dex */
final class zzgp implements InterfaceC1084d {
    private static final C1083c zzA;
    private static final C1083c zzB;
    private static final C1083c zzC;
    private static final C1083c zzD;
    private static final C1083c zzE;
    private static final C1083c zzF;
    private static final C1083c zzG;
    private static final C1083c zzH;
    private static final C1083c zzI;
    private static final C1083c zzJ;
    private static final C1083c zzK;
    private static final C1083c zzL;
    private static final C1083c zzM;
    private static final C1083c zzN;
    private static final C1083c zzO;
    private static final C1083c zzP;
    private static final C1083c zzQ;
    private static final C1083c zzR;
    private static final C1083c zzS;
    private static final C1083c zzT;
    private static final C1083c zzU;
    private static final C1083c zzV;
    private static final C1083c zzW;
    private static final C1083c zzX;
    private static final C1083c zzY;
    private static final C1083c zzZ;
    static final zzgp zza = new zzgp();
    private static final C1083c zzaA;
    private static final C1083c zzaB;
    private static final C1083c zzaC;
    private static final C1083c zzaD;
    private static final C1083c zzaE;
    private static final C1083c zzaF;
    private static final C1083c zzaG;
    private static final C1083c zzaH;
    private static final C1083c zzaI;
    private static final C1083c zzaJ;
    private static final C1083c zzaK;
    private static final C1083c zzaL;
    private static final C1083c zzaM;
    private static final C1083c zzaN;
    private static final C1083c zzaO;
    private static final C1083c zzaP;
    private static final C1083c zzaQ;
    private static final C1083c zzaR;
    private static final C1083c zzaS;
    private static final C1083c zzaT;
    private static final C1083c zzaU;
    private static final C1083c zzaV;
    private static final C1083c zzaW;
    private static final C1083c zzaX;
    private static final C1083c zzaY;
    private static final C1083c zzaZ;
    private static final C1083c zzaa;
    private static final C1083c zzab;
    private static final C1083c zzac;
    private static final C1083c zzad;
    private static final C1083c zzae;
    private static final C1083c zzaf;
    private static final C1083c zzag;
    private static final C1083c zzah;
    private static final C1083c zzai;
    private static final C1083c zzaj;
    private static final C1083c zzak;
    private static final C1083c zzal;
    private static final C1083c zzam;
    private static final C1083c zzan;
    private static final C1083c zzao;
    private static final C1083c zzap;
    private static final C1083c zzaq;
    private static final C1083c zzar;
    private static final C1083c zzas;
    private static final C1083c zzat;
    private static final C1083c zzau;
    private static final C1083c zzav;
    private static final C1083c zzaw;
    private static final C1083c zzax;
    private static final C1083c zzay;
    private static final C1083c zzaz;
    private static final C1083c zzb;
    private static final C1083c zzba;
    private static final C1083c zzbb;
    private static final C1083c zzbc;
    private static final C1083c zzbd;
    private static final C1083c zzbe;
    private static final C1083c zzbf;
    private static final C1083c zzbg;
    private static final C1083c zzbh;
    private static final C1083c zzbi;
    private static final C1083c zzbj;
    private static final C1083c zzbk;
    private static final C1083c zzbl;
    private static final C1083c zzbm;
    private static final C1083c zzbn;
    private static final C1083c zzbo;
    private static final C1083c zzbp;
    private static final C1083c zzbq;
    private static final C1083c zzbr;
    private static final C1083c zzbs;
    private static final C1083c zzbt;
    private static final C1083c zzbu;
    private static final C1083c zzbv;
    private static final C1083c zzbw;
    private static final C1083c zzbx;
    private static final C1083c zzby;
    private static final C1083c zzc;
    private static final C1083c zzd;
    private static final C1083c zze;
    private static final C1083c zzf;
    private static final C1083c zzg;
    private static final C1083c zzh;
    private static final C1083c zzi;
    private static final C1083c zzj;
    private static final C1083c zzk;
    private static final C1083c zzl;
    private static final C1083c zzm;
    private static final C1083c zzn;
    private static final C1083c zzo;
    private static final C1083c zzp;
    private static final C1083c zzq;
    private static final C1083c zzr;
    private static final C1083c zzs;
    private static final C1083c zzt;
    private static final C1083c zzu;
    private static final C1083c zzv;
    private static final C1083c zzw;
    private static final C1083c zzx;
    private static final C1083c zzy;
    private static final C1083c zzz;

    static {
        zzbc e7 = Y.e(1);
        HashMap hashMap = new HashMap();
        hashMap.put(e7.annotationType(), e7);
        zzb = new C1083c("systemInfo", Y.n(hashMap));
        zzbc e8 = Y.e(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(e8.annotationType(), e8);
        zzc = new C1083c("eventName", Y.n(hashMap2));
        zzbc e9 = Y.e(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(e9.annotationType(), e9);
        zzd = new C1083c("isThickClient", Y.n(hashMap3));
        zzbc e10 = Y.e(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(e10.annotationType(), e10);
        zze = new C1083c("clientType", Y.n(hashMap4));
        zzbc e11 = Y.e(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(e11.annotationType(), e11);
        zzf = new C1083c("modelDownloadLogEvent", Y.n(hashMap5));
        zzbc e12 = Y.e(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(e12.annotationType(), e12);
        zzg = new C1083c("customModelLoadLogEvent", Y.n(hashMap6));
        zzbc e13 = Y.e(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(e13.annotationType(), e13);
        zzh = new C1083c("customModelInferenceLogEvent", Y.n(hashMap7));
        zzbc e14 = Y.e(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(e14.annotationType(), e14);
        zzi = new C1083c("customModelCreateLogEvent", Y.n(hashMap8));
        zzbc e15 = Y.e(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(e15.annotationType(), e15);
        zzj = new C1083c("onDeviceFaceDetectionLogEvent", Y.n(hashMap9));
        zzbc e16 = Y.e(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(e16.annotationType(), e16);
        zzk = new C1083c("onDeviceFaceLoadLogEvent", Y.n(hashMap10));
        zzbc e17 = Y.e(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(e17.annotationType(), e17);
        zzl = new C1083c("onDeviceTextDetectionLogEvent", Y.n(hashMap11));
        zzbc e18 = Y.e(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(e18.annotationType(), e18);
        zzm = new C1083c("onDeviceTextDetectionLoadLogEvent", Y.n(hashMap12));
        zzbc e19 = Y.e(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(e19.annotationType(), e19);
        zzn = new C1083c("onDeviceBarcodeDetectionLogEvent", Y.n(hashMap13));
        zzbc e20 = Y.e(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(e20.annotationType(), e20);
        zzo = new C1083c("onDeviceBarcodeLoadLogEvent", Y.n(hashMap14));
        zzbc e21 = Y.e(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(e21.annotationType(), e21);
        zzp = new C1083c("onDeviceImageLabelCreateLogEvent", Y.n(hashMap15));
        zzbc e22 = Y.e(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(e22.annotationType(), e22);
        zzq = new C1083c("onDeviceImageLabelLoadLogEvent", Y.n(hashMap16));
        zzbc e23 = Y.e(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(e23.annotationType(), e23);
        zzr = new C1083c("onDeviceImageLabelDetectionLogEvent", Y.n(hashMap17));
        zzbc e24 = Y.e(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(e24.annotationType(), e24);
        zzs = new C1083c("onDeviceObjectCreateLogEvent", Y.n(hashMap18));
        zzbc e25 = Y.e(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(e25.annotationType(), e25);
        zzt = new C1083c("onDeviceObjectLoadLogEvent", Y.n(hashMap19));
        zzbc e26 = Y.e(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(e26.annotationType(), e26);
        zzu = new C1083c("onDeviceObjectInferenceLogEvent", Y.n(hashMap20));
        zzbc e27 = Y.e(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(e27.annotationType(), e27);
        zzv = new C1083c("onDevicePoseDetectionLogEvent", Y.n(hashMap21));
        zzbc e28 = Y.e(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(e28.annotationType(), e28);
        zzw = new C1083c("onDeviceSegmentationLogEvent", Y.n(hashMap22));
        zzbc e29 = Y.e(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(e29.annotationType(), e29);
        zzx = new C1083c("onDeviceSmartReplyLogEvent", Y.n(hashMap23));
        zzbc e30 = Y.e(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(e30.annotationType(), e30);
        zzy = new C1083c("onDeviceLanguageIdentificationLogEvent", Y.n(hashMap24));
        zzbc e31 = Y.e(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(e31.annotationType(), e31);
        zzz = new C1083c("onDeviceTranslationLogEvent", Y.n(hashMap25));
        zzbc e32 = Y.e(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(e32.annotationType(), e32);
        zzA = new C1083c("cloudFaceDetectionLogEvent", Y.n(hashMap26));
        zzbc e33 = Y.e(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(e33.annotationType(), e33);
        zzB = new C1083c("cloudCropHintDetectionLogEvent", Y.n(hashMap27));
        zzbc e34 = Y.e(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(e34.annotationType(), e34);
        zzC = new C1083c("cloudDocumentTextDetectionLogEvent", Y.n(hashMap28));
        zzbc e35 = Y.e(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(e35.annotationType(), e35);
        zzD = new C1083c("cloudImagePropertiesDetectionLogEvent", Y.n(hashMap29));
        zzbc e36 = Y.e(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(e36.annotationType(), e36);
        zzE = new C1083c("cloudImageLabelDetectionLogEvent", Y.n(hashMap30));
        zzbc e37 = Y.e(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(e37.annotationType(), e37);
        zzF = new C1083c("cloudLandmarkDetectionLogEvent", Y.n(hashMap31));
        zzbc e38 = Y.e(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(e38.annotationType(), e38);
        zzG = new C1083c("cloudLogoDetectionLogEvent", Y.n(hashMap32));
        zzbc e39 = Y.e(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(e39.annotationType(), e39);
        zzH = new C1083c("cloudSafeSearchDetectionLogEvent", Y.n(hashMap33));
        zzbc e40 = Y.e(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(e40.annotationType(), e40);
        zzI = new C1083c("cloudTextDetectionLogEvent", Y.n(hashMap34));
        zzbc e41 = Y.e(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(e41.annotationType(), e41);
        zzJ = new C1083c("cloudWebSearchDetectionLogEvent", Y.n(hashMap35));
        zzbc e42 = Y.e(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(e42.annotationType(), e42);
        zzK = new C1083c("automlImageLabelingCreateLogEvent", Y.n(hashMap36));
        zzbc e43 = Y.e(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(e43.annotationType(), e43);
        zzL = new C1083c("automlImageLabelingLoadLogEvent", Y.n(hashMap37));
        zzbc e44 = Y.e(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(e44.annotationType(), e44);
        zzM = new C1083c("automlImageLabelingInferenceLogEvent", Y.n(hashMap38));
        zzbc e45 = Y.e(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(e45.annotationType(), e45);
        zzN = new C1083c("isModelDownloadedLogEvent", Y.n(hashMap39));
        zzbc e46 = Y.e(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(e46.annotationType(), e46);
        zzO = new C1083c("deleteModelLogEvent", Y.n(hashMap40));
        zzbc e47 = Y.e(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(e47.annotationType(), e47);
        zzP = new C1083c("aggregatedAutomlImageLabelingInferenceLogEvent", Y.n(hashMap41));
        zzbc e48 = Y.e(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(e48.annotationType(), e48);
        zzQ = new C1083c("aggregatedCustomModelInferenceLogEvent", Y.n(hashMap42));
        zzbc e49 = Y.e(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(e49.annotationType(), e49);
        zzR = new C1083c("aggregatedOnDeviceFaceDetectionLogEvent", Y.n(hashMap43));
        zzbc e50 = Y.e(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(e50.annotationType(), e50);
        zzS = new C1083c("aggregatedOnDeviceBarcodeDetectionLogEvent", Y.n(hashMap44));
        zzbc e51 = Y.e(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(e51.annotationType(), e51);
        zzT = new C1083c("aggregatedOnDeviceImageLabelDetectionLogEvent", Y.n(hashMap45));
        zzbc e52 = Y.e(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(e52.annotationType(), e52);
        zzU = new C1083c("aggregatedOnDeviceObjectInferenceLogEvent", Y.n(hashMap46));
        zzbc e53 = Y.e(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(e53.annotationType(), e53);
        zzV = new C1083c("aggregatedOnDeviceTextDetectionLogEvent", Y.n(hashMap47));
        zzbc e54 = Y.e(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(e54.annotationType(), e54);
        zzW = new C1083c("aggregatedOnDevicePoseDetectionLogEvent", Y.n(hashMap48));
        zzbc e55 = Y.e(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(e55.annotationType(), e55);
        zzX = new C1083c("aggregatedOnDeviceSegmentationLogEvent", Y.n(hashMap49));
        zzbc e56 = Y.e(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(e56.annotationType(), e56);
        zzY = new C1083c("pipelineAccelerationInferenceEvents", Y.n(hashMap50));
        zzbc e57 = Y.e(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(e57.annotationType(), e57);
        zzZ = new C1083c("remoteConfigLogEvent", Y.n(hashMap51));
        zzbc e58 = Y.e(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(e58.annotationType(), e58);
        zzaa = new C1083c("inputImageConstructionLogEvent", Y.n(hashMap52));
        zzbc e59 = Y.e(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(e59.annotationType(), e59);
        zzab = new C1083c("leakedHandleEvent", Y.n(hashMap53));
        zzbc e60 = Y.e(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(e60.annotationType(), e60);
        zzac = new C1083c("cameraSourceLogEvent", Y.n(hashMap54));
        zzbc e61 = Y.e(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(e61.annotationType(), e61);
        zzad = new C1083c("imageLabelOptionalModuleLogEvent", Y.n(hashMap55));
        zzbc e62 = Y.e(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(e62.annotationType(), e62);
        zzae = new C1083c("languageIdentificationOptionalModuleLogEvent", Y.n(hashMap56));
        zzbc e63 = Y.e(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(e63.annotationType(), e63);
        zzaf = new C1083c("faceDetectionOptionalModuleLogEvent", Y.n(hashMap57));
        zzbc e64 = Y.e(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(e64.annotationType(), e64);
        zzag = new C1083c("documentDetectionOptionalModuleLogEvent", Y.n(hashMap58));
        zzbc e65 = Y.e(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(e65.annotationType(), e65);
        zzah = new C1083c("documentCroppingOptionalModuleLogEvent", Y.n(hashMap59));
        zzbc e66 = Y.e(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(e66.annotationType(), e66);
        zzai = new C1083c("documentEnhancementOptionalModuleLogEvent", Y.n(hashMap60));
        zzbc e67 = Y.e(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(e67.annotationType(), e67);
        zzaj = new C1083c("nlClassifierOptionalModuleLogEvent", Y.n(hashMap61));
        zzbc e68 = Y.e(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(e68.annotationType(), e68);
        zzak = new C1083c("nlClassifierClientLibraryLogEvent", Y.n(hashMap62));
        zzbc e69 = Y.e(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(e69.annotationType(), e69);
        zzal = new C1083c("accelerationAllowlistLogEvent", Y.n(hashMap63));
        zzbc e70 = Y.e(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(e70.annotationType(), e70);
        zzam = new C1083c("toxicityDetectionCreateEvent", Y.n(hashMap64));
        zzbc e71 = Y.e(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(e71.annotationType(), e71);
        zzan = new C1083c("toxicityDetectionLoadEvent", Y.n(hashMap65));
        zzbc e72 = Y.e(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(e72.annotationType(), e72);
        zzao = new C1083c("toxicityDetectionInferenceEvent", Y.n(hashMap66));
        zzbc e73 = Y.e(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(e73.annotationType(), e73);
        zzap = new C1083c("barcodeDetectionOptionalModuleLogEvent", Y.n(hashMap67));
        zzbc e74 = Y.e(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(e74.annotationType(), e74);
        zzaq = new C1083c("customImageLabelOptionalModuleLogEvent", Y.n(hashMap68));
        zzbc e75 = Y.e(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(e75.annotationType(), e75);
        zzar = new C1083c("codeScannerScanApiEvent", Y.n(hashMap69));
        zzbc e76 = Y.e(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(e76.annotationType(), e76);
        zzas = new C1083c("codeScannerOptionalModuleEvent", Y.n(hashMap70));
        zzbc e77 = Y.e(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(e77.annotationType(), e77);
        zzat = new C1083c("onDeviceExplicitContentCreateLogEvent", Y.n(hashMap71));
        zzbc e78 = Y.e(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(e78.annotationType(), e78);
        zzau = new C1083c("onDeviceExplicitContentLoadLogEvent", Y.n(hashMap72));
        zzbc e79 = Y.e(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(e79.annotationType(), e79);
        zzav = new C1083c("onDeviceExplicitContentInferenceLogEvent", Y.n(hashMap73));
        zzbc e80 = Y.e(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(e80.annotationType(), e80);
        zzaw = new C1083c("aggregatedOnDeviceExplicitContentLogEvent", Y.n(hashMap74));
        zzbc e81 = Y.e(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(e81.annotationType(), e81);
        zzax = new C1083c("onDeviceFaceMeshCreateLogEvent", Y.n(hashMap75));
        zzbc e82 = Y.e(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(e82.annotationType(), e82);
        zzay = new C1083c("onDeviceFaceMeshLoadLogEvent", Y.n(hashMap76));
        zzbc e83 = Y.e(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(e83.annotationType(), e83);
        zzaz = new C1083c("onDeviceFaceMeshLogEvent", Y.n(hashMap77));
        zzbc e84 = Y.e(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(e84.annotationType(), e84);
        zzaA = new C1083c("aggregatedOnDeviceFaceMeshLogEvent", Y.n(hashMap78));
        zzbc e85 = Y.e(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(e85.annotationType(), e85);
        zzaB = new C1083c("smartReplyOptionalModuleLogEvent", Y.n(hashMap79));
        zzbc e86 = Y.e(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(e86.annotationType(), e86);
        zzaC = new C1083c("textDetectionOptionalModuleLogEvent", Y.n(hashMap80));
        zzbc e87 = Y.e(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(e87.annotationType(), e87);
        zzaD = new C1083c("onDeviceImageQualityAnalysisCreateLogEvent", Y.n(hashMap81));
        zzbc e88 = Y.e(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(e88.annotationType(), e88);
        zzaE = new C1083c("onDeviceImageQualityAnalysisLoadLogEvent", Y.n(hashMap82));
        zzbc e89 = Y.e(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(e89.annotationType(), e89);
        zzaF = new C1083c("onDeviceImageQualityAnalysisLogEvent", Y.n(hashMap83));
        zzbc e90 = Y.e(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(e90.annotationType(), e90);
        zzaG = new C1083c("aggregatedOnDeviceImageQualityAnalysisLogEvent", Y.n(hashMap84));
        zzbc e91 = Y.e(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(e91.annotationType(), e91);
        zzaH = new C1083c("imageQualityAnalysisOptionalModuleLogEvent", Y.n(hashMap85));
        zzbc e92 = Y.e(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(e92.annotationType(), e92);
        zzaI = new C1083c("imageCaptioningOptionalModuleLogEvent", Y.n(hashMap86));
        zzbc e93 = Y.e(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(e93.annotationType(), e93);
        zzaJ = new C1083c("onDeviceImageCaptioningCreateLogEvent", Y.n(hashMap87));
        zzbc e94 = Y.e(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(e94.annotationType(), e94);
        zzaK = new C1083c("onDeviceImageCaptioningLoadLogEvent", Y.n(hashMap88));
        zzbc e95 = Y.e(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(e95.annotationType(), e95);
        zzaL = new C1083c("onDeviceImageCaptioningInferenceLogEvent", Y.n(hashMap89));
        zzbc e96 = Y.e(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(e96.annotationType(), e96);
        zzaM = new C1083c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", Y.n(hashMap90));
        zzbc e97 = Y.e(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(e97.annotationType(), e97);
        zzaN = new C1083c("onDeviceDocumentDetectionCreateLogEvent", Y.n(hashMap91));
        zzbc e98 = Y.e(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(e98.annotationType(), e98);
        zzaO = new C1083c("onDeviceDocumentDetectionLoadLogEvent", Y.n(hashMap92));
        zzbc e99 = Y.e(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(e99.annotationType(), e99);
        zzaP = new C1083c("onDeviceDocumentDetectionLogEvent", Y.n(hashMap93));
        zzbc e100 = Y.e(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(e100.annotationType(), e100);
        zzaQ = new C1083c("aggregatedOnDeviceDocumentDetectionLogEvent", Y.n(hashMap94));
        zzbc e101 = Y.e(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(e101.annotationType(), e101);
        zzaR = new C1083c("onDeviceDocumentCroppingCreateLogEvent", Y.n(hashMap95));
        zzbc e102 = Y.e(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(e102.annotationType(), e102);
        zzaS = new C1083c("onDeviceDocumentCroppingLoadLogEvent", Y.n(hashMap96));
        zzbc e103 = Y.e(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(e103.annotationType(), e103);
        zzaT = new C1083c("onDeviceDocumentCroppingLogEvent", Y.n(hashMap97));
        zzbc e104 = Y.e(101);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(e104.annotationType(), e104);
        zzaU = new C1083c("aggregatedOnDeviceDocumentCroppingLogEvent", Y.n(hashMap98));
        zzbc e105 = Y.e(102);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(e105.annotationType(), e105);
        zzaV = new C1083c("onDeviceDocumentEnhancementCreateLogEvent", Y.n(hashMap99));
        zzbc e106 = Y.e(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(e106.annotationType(), e106);
        zzaW = new C1083c("onDeviceDocumentEnhancementLoadLogEvent", Y.n(hashMap100));
        zzbc e107 = Y.e(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(e107.annotationType(), e107);
        zzaX = new C1083c("onDeviceDocumentEnhancementLogEvent", Y.n(hashMap101));
        zzbc e108 = Y.e(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(e108.annotationType(), e108);
        zzaY = new C1083c("aggregatedOnDeviceDocumentEnhancementLogEvent", Y.n(hashMap102));
        zzbc e109 = Y.e(106);
        HashMap hashMap103 = new HashMap();
        hashMap103.put(e109.annotationType(), e109);
        zzaZ = new C1083c("scannerAutoZoomEvent", Y.n(hashMap103));
        zzbc e110 = Y.e(107);
        HashMap hashMap104 = new HashMap();
        hashMap104.put(e110.annotationType(), e110);
        zzba = new C1083c("lowLightAutoExposureComputationEvent", Y.n(hashMap104));
        zzbc e111 = Y.e(108);
        HashMap hashMap105 = new HashMap();
        hashMap105.put(e111.annotationType(), e111);
        zzbb = new C1083c("lowLightFrameProcessEvent", Y.n(hashMap105));
        zzbc e112 = Y.e(109);
        HashMap hashMap106 = new HashMap();
        hashMap106.put(e112.annotationType(), e112);
        zzbc = new C1083c("lowLightSceneDetectionEvent", Y.n(hashMap106));
        zzbc e113 = Y.e(110);
        HashMap hashMap107 = new HashMap();
        hashMap107.put(e113.annotationType(), e113);
        zzbd = new C1083c("onDeviceStainRemovalLogEvent", Y.n(hashMap107));
        zzbc e114 = Y.e(111);
        HashMap hashMap108 = new HashMap();
        hashMap108.put(e114.annotationType(), e114);
        zzbe = new C1083c("aggregatedOnDeviceStainRemovalLogEvent", Y.n(hashMap108));
        zzbf = Y.j(112, C1083c.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = Y.j(113, C1083c.a("onDeviceShadowRemovalLogEvent"));
        zzbh = Y.j(114, C1083c.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = Y.j(115, C1083c.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = Y.j(116, C1083c.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = Y.j(117, C1083c.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = Y.j(118, C1083c.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = Y.j(119, C1083c.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = Y.j(120, C1083c.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = Y.j(121, C1083c.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = Y.j(122, C1083c.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = Y.j(123, C1083c.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = Y.j(124, C1083c.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = Y.j(125, C1083c.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = Y.j(126, C1083c.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = Y.j(127, C1083c.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = Y.j(RecognitionOptions.ITF, C1083c.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = Y.j(129, C1083c.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = Y.j(130, C1083c.a("documentScannerUiModuleScreenClickEvent"));
        zzby = Y.j(131, C1083c.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzgp() {
    }

    @Override // h4.InterfaceC1081a
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzmy zzmyVar = (zzmy) obj;
        InterfaceC1085e interfaceC1085e = (InterfaceC1085e) obj2;
        interfaceC1085e.add(zzb, zzmyVar.zzf());
        interfaceC1085e.add(zzc, zzmyVar.zzd());
        interfaceC1085e.add(zzd, (Object) null);
        interfaceC1085e.add(zze, (Object) null);
        interfaceC1085e.add(zzf, zzmyVar.zze());
        interfaceC1085e.add(zzg, (Object) null);
        interfaceC1085e.add(zzh, (Object) null);
        interfaceC1085e.add(zzi, (Object) null);
        interfaceC1085e.add(zzj, (Object) null);
        interfaceC1085e.add(zzk, (Object) null);
        interfaceC1085e.add(zzl, (Object) null);
        interfaceC1085e.add(zzm, (Object) null);
        interfaceC1085e.add(zzn, (Object) null);
        interfaceC1085e.add(zzo, (Object) null);
        interfaceC1085e.add(zzp, (Object) null);
        interfaceC1085e.add(zzq, (Object) null);
        interfaceC1085e.add(zzr, (Object) null);
        interfaceC1085e.add(zzs, (Object) null);
        interfaceC1085e.add(zzt, (Object) null);
        interfaceC1085e.add(zzu, (Object) null);
        interfaceC1085e.add(zzv, (Object) null);
        interfaceC1085e.add(zzw, (Object) null);
        interfaceC1085e.add(zzx, (Object) null);
        interfaceC1085e.add(zzy, (Object) null);
        interfaceC1085e.add(zzz, (Object) null);
        interfaceC1085e.add(zzA, (Object) null);
        interfaceC1085e.add(zzB, (Object) null);
        interfaceC1085e.add(zzC, (Object) null);
        interfaceC1085e.add(zzD, (Object) null);
        interfaceC1085e.add(zzE, (Object) null);
        interfaceC1085e.add(zzF, (Object) null);
        interfaceC1085e.add(zzG, (Object) null);
        interfaceC1085e.add(zzH, (Object) null);
        interfaceC1085e.add(zzI, (Object) null);
        interfaceC1085e.add(zzJ, (Object) null);
        interfaceC1085e.add(zzK, (Object) null);
        interfaceC1085e.add(zzL, (Object) null);
        interfaceC1085e.add(zzM, (Object) null);
        interfaceC1085e.add(zzN, zzmyVar.zzb());
        interfaceC1085e.add(zzO, zzmyVar.zza());
        interfaceC1085e.add(zzP, (Object) null);
        interfaceC1085e.add(zzQ, (Object) null);
        interfaceC1085e.add(zzR, (Object) null);
        interfaceC1085e.add(zzS, (Object) null);
        interfaceC1085e.add(zzT, (Object) null);
        interfaceC1085e.add(zzU, (Object) null);
        interfaceC1085e.add(zzV, (Object) null);
        interfaceC1085e.add(zzW, (Object) null);
        interfaceC1085e.add(zzX, (Object) null);
        interfaceC1085e.add(zzY, (Object) null);
        interfaceC1085e.add(zzZ, (Object) null);
        interfaceC1085e.add(zzaa, (Object) null);
        interfaceC1085e.add(zzab, zzmyVar.zzc());
        interfaceC1085e.add(zzac, (Object) null);
        interfaceC1085e.add(zzad, (Object) null);
        interfaceC1085e.add(zzae, (Object) null);
        interfaceC1085e.add(zzaf, (Object) null);
        interfaceC1085e.add(zzag, (Object) null);
        interfaceC1085e.add(zzah, (Object) null);
        interfaceC1085e.add(zzai, (Object) null);
        interfaceC1085e.add(zzaj, (Object) null);
        interfaceC1085e.add(zzak, (Object) null);
        interfaceC1085e.add(zzal, (Object) null);
        interfaceC1085e.add(zzam, (Object) null);
        interfaceC1085e.add(zzan, (Object) null);
        interfaceC1085e.add(zzao, (Object) null);
        interfaceC1085e.add(zzap, (Object) null);
        interfaceC1085e.add(zzaq, (Object) null);
        interfaceC1085e.add(zzar, (Object) null);
        interfaceC1085e.add(zzas, (Object) null);
        interfaceC1085e.add(zzat, (Object) null);
        interfaceC1085e.add(zzau, (Object) null);
        interfaceC1085e.add(zzav, (Object) null);
        interfaceC1085e.add(zzaw, (Object) null);
        interfaceC1085e.add(zzax, (Object) null);
        interfaceC1085e.add(zzay, (Object) null);
        interfaceC1085e.add(zzaz, (Object) null);
        interfaceC1085e.add(zzaA, (Object) null);
        interfaceC1085e.add(zzaB, (Object) null);
        interfaceC1085e.add(zzaC, (Object) null);
        interfaceC1085e.add(zzaD, (Object) null);
        interfaceC1085e.add(zzaE, (Object) null);
        interfaceC1085e.add(zzaF, (Object) null);
        interfaceC1085e.add(zzaG, (Object) null);
        interfaceC1085e.add(zzaH, (Object) null);
        interfaceC1085e.add(zzaI, (Object) null);
        interfaceC1085e.add(zzaJ, (Object) null);
        interfaceC1085e.add(zzaK, (Object) null);
        interfaceC1085e.add(zzaL, (Object) null);
        interfaceC1085e.add(zzaM, (Object) null);
        interfaceC1085e.add(zzaN, (Object) null);
        interfaceC1085e.add(zzaO, (Object) null);
        interfaceC1085e.add(zzaP, (Object) null);
        interfaceC1085e.add(zzaQ, (Object) null);
        interfaceC1085e.add(zzaR, (Object) null);
        interfaceC1085e.add(zzaS, (Object) null);
        interfaceC1085e.add(zzaT, (Object) null);
        interfaceC1085e.add(zzaU, (Object) null);
        interfaceC1085e.add(zzaV, (Object) null);
        interfaceC1085e.add(zzaW, (Object) null);
        interfaceC1085e.add(zzaX, (Object) null);
        interfaceC1085e.add(zzaY, (Object) null);
        interfaceC1085e.add(zzaZ, (Object) null);
        interfaceC1085e.add(zzba, (Object) null);
        interfaceC1085e.add(zzbb, (Object) null);
        interfaceC1085e.add(zzbc, (Object) null);
        interfaceC1085e.add(zzbd, (Object) null);
        interfaceC1085e.add(zzbe, (Object) null);
        interfaceC1085e.add(zzbf, (Object) null);
        interfaceC1085e.add(zzbg, (Object) null);
        interfaceC1085e.add(zzbh, (Object) null);
        interfaceC1085e.add(zzbi, (Object) null);
        interfaceC1085e.add(zzbj, (Object) null);
        interfaceC1085e.add(zzbk, (Object) null);
        interfaceC1085e.add(zzbl, (Object) null);
        interfaceC1085e.add(zzbm, (Object) null);
        interfaceC1085e.add(zzbn, (Object) null);
        interfaceC1085e.add(zzbo, (Object) null);
        interfaceC1085e.add(zzbp, (Object) null);
        interfaceC1085e.add(zzbq, (Object) null);
        interfaceC1085e.add(zzbr, (Object) null);
        interfaceC1085e.add(zzbs, (Object) null);
        interfaceC1085e.add(zzbt, (Object) null);
        interfaceC1085e.add(zzbu, (Object) null);
        interfaceC1085e.add(zzbv, (Object) null);
        interfaceC1085e.add(zzbw, (Object) null);
        interfaceC1085e.add(zzbx, (Object) null);
        interfaceC1085e.add(zzby, (Object) null);
    }
}
